using UnityEngine;

[RequireComponent(typeof(GimmickSubject))]

public class TriggerObject : MonoBehaviour
{
    private GimmickSubject subject;

    void Awake()
    {
        subject = GetComponent<GimmickSubject>();
    }

    void OnTriggerEnter(Collider other)
    {
        if (other.CompareTag("Player"))
        {
            Debug.Log("ЦЎИЎАХ НЧЧр.");
            subject.Notify();  // ЕщОюПдРЛ ЖЇ ОЫИВ
        }
    }

    void OnTriggerExit(Collider other)
    {
        if (other.CompareTag("Player"))
        {
            Debug.Log("ЦЎИЎАХ СОЗс.");
            subject.NotifyExit();  // ГЊАЌРЛ ЖЇ ОЫИВ
        }
    }
}
