using Unity.VisualScripting;
using UnityEngine;
using UnityEngine.UI;

public class ReadyButton : MonoBehaviour
{
    private Image buttonImage; // น๖ฦฐ ภฬนฬม๖ ฤฤฦ๗ณอฦฎ
    private Color color1 = new Color(255f / 255f, 174f / 255f, 174f / 255f, 0.5f); // รสฑโ ป๖ป๓ (ฟฌวั ปกฐญ)
    private Color color2 = new Color(196f / 255f, 233f / 255f, 255f / 255f, 0.5f); // บฏฐๆวา ป๖ป๓ (ฟฌวั ฦฤถ๛)

    // Start is called once before the first execution of Update after the MonoBehaviour is created
    void Start()
    {
        //น๖ฦฐภว ภฬนฬม๖ ฤฤฦ๗ณอฦฎ ฐกมฎฟภฑโ
        buttonImage = GetComponent<Image>();

        //รสฑโ น๖ฦฐ ป๖ฑ๒ ผณมค
        buttonImage.color = color1;

        //น๖ฦฐ ฤฤฦ๗ณอฦฎธฆ ฐกมฎฟอ ลฌธฏ ภฬบฅฦฎฟก วิผ๖ ร฿ฐก
        GetComponent<Button>().onClick.AddListener(ChangeColor);
    }

    // Update is called once per frame
    void Update()
    {
        
    }

    void ChangeColor()
    {
        //น๖ฦฐ ป๖ฑ๒ บฏฐๆ
        if (buttonImage.color.Equals(color1))
            buttonImage.color = color2;
        else if (buttonImage.color.Equals(color2))
            buttonImage.color = color1;

    }
}
