using UnityEngine;
using UnityEngine.UI;

public class InteractionUIButton : MonoBehaviour
{
    public Button interactButton; // UI น๖ฦฐ

    private TeleportObject currentTeleportObject;

    void Start()
    {
        // น๖ฦฐ ลฌธฏ ภฬบฅฦฎฟก วิผ๖ ฟฌฐแ
        interactButton.onClick.AddListener(OnInteractButtonClicked);
        interactButton.gameObject.SetActive(false); // รสฑโฟกดย บ๑ศฐผบศญ
    }

    void Update()
    {
        // ลฺทนฦ๗ฦฎ ฟภบ๊มงฦฎ มึบฏฟก ภึภป ถง น๖ฦฐ ศฐผบศญ
        if (currentTeleportObject != null)
        {
            interactButton.gameObject.SetActive(true);
        }
        else
        {
            interactButton.gameObject.SetActive(false);
        }
    }

    private void OnInteractButtonClicked()
    {
        if (currentTeleportObject != null)
        {
            currentTeleportObject.TeleportPlayer();
        }
    }

    private void OnTriggerEnter(Collider other)
    {
        if (other.CompareTag("Teleport"))
        {
            currentTeleportObject = other.GetComponent<TeleportObject>();
        }
    }

    private void OnTriggerExit(Collider other)
    {
        if (other.CompareTag("Teleport"))
        {
            currentTeleportObject = null;
        }
    }
}